# Generated by Django 5.1.4 on 2025-01-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_trans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
