# Generated by Django 5.1.4 on 2025-01-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_trans', '0002_transaction_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('recharge', 'Поповнення'), ('transfer', 'Переведення')], default='recharge', max_length=50),
        ),
    ]
