# Generated by Django 5.1.4 on 2025-02-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banka',
            name='goal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='banka',
            name='hash_code',
            field=models.CharField(default='a1d75fba7353', max_length=12, unique=True),
        ),
    ]
