# Generated by Django 5.1.4 on 2025-03-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_banka_hash_code_usercashback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banka',
            name='hash_code',
            field=models.CharField(default='c5c527ba6b4d', max_length=12, unique=True),
        ),
    ]
