# Generated by Django 5.1.4 on 2025-03-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_banka_hash_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banka',
            name='hash_code',
            field=models.CharField(default='3853473f8d10', max_length=12, unique=True),
        ),
    ]
