# Generated by Django 5.1.3 on 2025-03-15 12:54

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_banka_hash_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banka',
            name='goal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[cards.models.validate_goal]),
        ),
        migrations.AlterField(
            model_name='banka',
            name='hash_code',
            field=models.CharField(default='2a1a20fefbc6', max_length=12, unique=True),
        ),
    ]
