# Generated by Django 5.1.3 on 2025-01-12 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_auth', '0003_alter_bankcard_balance_alter_bankcard_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
