# Generated by Django 5.1.4 on 2025-02-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_auth', '0004_alter_bankcard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
